title: Digital Industry Singapore
url: https://www.disg.gov.sg
favicon: /images/disg_logo_favicon.png
colors:
  primary-color: "#23b9db"
  secondary-color: "#403e86"
  media-colors:
    - title: media-color-one
      color: "#e30613"
    - title: media-color-two
      color: "#353534"
    - title: media-color-three
      color: "#ffffff"
    - title: media-color-four
      color: "#ffffff"
    - title: media-color-five
      color: "#ffffff"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3wd0sa7npb1u.amplifyapp.com
prod: https://master.d3wd0sa7npb1u.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: test-1
